Using the unique_day function with the wrong argument (i[1]) instead of (i[0]).