This location is potentially faulty because it breaks out of the inner while loop instead of the outer for loop.